---
    environment: production
    address: 127.0.0.1
    port: 4618
    pid: thin.pid
    rackup: config.ru
    log: thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true
